package io.github.enerccio.llllm.loc;

public enum L {

    BUTTON_EXIT,
    LABEL_USERNAME,
    LABEL_LOGIN,
    LABEL_LOGOUT,
    LABEL_EXIT_APPLICATION,
    LABEL_USER_FULLNAME,
    LABEL_EMAIL,
    LABEL_PASSWORD,
    LABEL_PASSWORD_AGAIN,
    LABEL_FORGOT_PASSWORD,
    LABEL_SAVE_LOGIN,
    LABEL_AUTHENTICATION_FAILED,
    LABEL_APPLICATION_ERROR,
    INTERNAL_SERVER_ERROR,
    MSG_VALIDATION_FAILED_CANNONT_SAVE,
    MSG_VALIDATION_FAILED_CANNONT_SAVE_EXT,
    MSG_AUTHENTICATION_FAILED_INFO,
    BUTTON_LOGIN,

}
